GET http://localhost:3000

### Criar um novo usuário
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Aluno",
  "email": "aluno2@mail.com",
  "password": "aluno123",
  "role": "STUDENT"
}